# Generated by Django 6.0.5 on 2026-05-29 11:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_product_description_and_more'),
        ('sales', '0002_remove_sale_sale_price_sale_discount_percent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Продажа', 'verbose_name_plural': 'Продажи'},
        ),
        migrations.AlterField(
            model_name='sale',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Себестоимость за 1 шт.'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Скидка, %'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='profit',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Прибыль'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_sale_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Сумма продажи'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_sale_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Цена за 1 шт. со скидкой'),
        ),
    ]
