# Generated by Django 6.0.5 on 2026-05-31 15:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_salecostallocation_stock_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='cost_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=10, verbose_name='Себестоимость за 1 шт.'),
        ),
    ]
