# Generated by Django 6.0.5 on 2026-06-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_salereturn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Продажу', 'verbose_name_plural': 'Продажи'},
        ),
    ]
