# Generated by Django 6.0.5 on 2026-05-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='contacts',
            field=models.TextField(blank=True, verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Заметки'),
        ),
    ]
