# Generated by Django 6.0.5 on 2026-06-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0002_alter_manufacturer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производителя', 'verbose_name_plural': 'Производители'},
        ),
    ]
