# Generated by Django 6.0.5 on 2026-05-29 11:06

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturers', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_date', models.DateField()),
                ('yuan_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('cargo_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5)),
                ('total_shipping_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_package_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('order_url', models.URLField(blank=True)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='manufacturers.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price_yuan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('china_shipping_yuan', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('product_cost_rub', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('allocated_shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('calculated_unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_items', to='products.product')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplies.supply')),
            ],
        ),
    ]
