# Generated by Django 6.0.5 on 2026-05-29 11:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturers', '0002_alter_manufacturer_options_and_more'),
        ('products', '0002_alter_product_options_alter_product_description_and_more'),
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name': 'Поставка', 'verbose_name_plural': 'Поставки'},
        ),
        migrations.AlterModelOptions(
            name='supplyitem',
            options={'verbose_name': 'Позиция поставки', 'verbose_name_plural': 'Позиции поставки'},
        ),
        migrations.AlterField(
            model_name='supply',
            name='cargo_commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5, verbose_name='Комиссия карго, %'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supplies', to='manufacturers.manufacturer', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='order_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на заказ'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='supply_date',
            field=models.DateField(verbose_name='Дата поставки'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='total_package_weight',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Вес с упаковкой, кг'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='total_shipping_cost',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Общая доставка, руб.'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='yuan_rate',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс юаня'),
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='allocated_shipping_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Доставка позиции, руб.'),
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='calculated_unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Себестоимость 1 шт., руб.'),
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='china_shipping_yuan',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Доставка по Китаю, юань'),
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='price_yuan',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за шт., юань'),
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supply_items', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='product_cost_rub',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Цена товара, руб.'),
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplies.supply', verbose_name='Поставка'),
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='unit_weight',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Вес 1 шт., кг'),
        ),
    ]
