# Generated by Django 6.0.5 on 2026-05-30 16:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_product_description_and_more'),
        ('supplies', '0002_alter_supply_options_alter_supplyitem_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualSupplyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Себестоимость 1 шт., руб.')),
                ('cost_note', models.TextField(blank=True, verbose_name='Примечание к себестоимости')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Итоговая себестоимость, руб.')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manual_supply_items', to='products.product', verbose_name='Товар')),
                ('supply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_items', to='supplies.supply', verbose_name='Поставка')),
            ],
            options={
                'verbose_name': 'Ручная позиция поставки',
                'verbose_name_plural': 'Ручные позиции поставки',
            },
        ),
    ]
