# Generated by Django 6.0.5 on 2026-05-30 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_manualsupplyitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_date', models.DateField(verbose_name='Дата поставки')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Ручная поставка',
                'verbose_name_plural': 'Ручные поставки',
            },
        ),
        migrations.AlterField(
            model_name='manualsupplyitem',
            name='supply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplies.manualsupply', verbose_name='Ручная поставка'),
        ),
    ]
