# Generated by Django 6.0.5 on 2026-06-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_remove_supply_manufacturer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name': 'Поставку', 'verbose_name_plural': 'Поставки'},
        ),
    ]
