# Generated by Django 6.0.5 on 2026-06-26 16:02

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0011_salereturn_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesSummaryReport',
            fields=[
            ],
            options={
                'verbose_name': 'Сводка продаж',
                'verbose_name_plural': 'Сводка продаж',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.sale',),
        ),
    ]
