"""
Django settings for japanese_sword project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
ENV_FILE = BASE_DIR.parent / ".env"  # путь к файлу .env


def load_env_file(path):
    if not path.exists():
        return

    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()

        if not line or line.startswith('#') or "=" not in line:
            continue

        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip())


def env_bool(name, default=False):
    value = os.environ.get(name)

    if value is None:
        return default

    return value.lower() in ("1", "true", "t", "yes", "on")


def env_list(name, default=""):
    value = os.environ.get(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


load_env_file(ENV_FILE)  # чтение .env файла с последующей записью в os.environ


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ["DJANGO_SECRET_KEY"]  # вытягиваем секретный ключ (value) через ключ словаря (key)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", default=False)  # затаем булево значение которое записано в .env

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS")  # выводим список из ip адресов

# CSRF_TRUSTED_ORIGINS — домены, с которых Django доверяет защищенным POST-запросам.
# Нужно для админки и форм, когда проект работает через HTTPS-домен.
CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS")

# CORS разрешает Vue dev server читать Django API в локальной разработке.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

# Токен Telegram-бота берем из .env, чтобы не хранить секрет в коде.
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "")

# Chat ID администратора нужен, чтобы Django знал, кому отправлять уведомления о заказах.
TELEGRAM_ADMIN_CHAT_ID = os.environ.get("TELEGRAM_ADMIN_CHAT_ID", "")


# Приложения которые видит проект

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',

    'manufacturers',
    'products',
    'stock',
    'supplies',
    'sales',
    'users',
    'orders',
    'reports',
]

AUTH_USER_MODEL = 'users.User'  # Используется кастомная модель user из соответствующего приложения

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'japanese_sword.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'japanese_sword.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        # Движок БД: PostgreSQL или SQLite, значение берем из .env.
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.sqlite3'),

        # Имя базы данных. Для PostgreSQL это имя БД, для SQLite - путь к файлу.
        'NAME': os.environ.get('DB_NAME', BASE_DIR / 'db.sqlite3'),

        # Пользователь PostgreSQL.
        'USER': os.environ.get('DB_USER', ''),

        # Пароль пользователя PostgreSQL.
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),

        # Адрес сервера PostgreSQL.
        'HOST': os.environ.get('DB_HOST', ''),

        # Порт PostgreSQL.
        'PORT': os.environ.get('DB_PORT', ''),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# STATIC_ROOT — папка, куда collectstatic соберет css/js/картинки Django для production.
STATIC_ROOT = BASE_DIR / 'staticfiles'

REST_FRAMEWORK = {
    # Специальная настройка DRF: класс пагинации по умолчанию
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',

    # Специальная настройка DRF: сколько объектов отдавать на одной странице
    'PAGE_SIZE': 20,
}

# MEDIA_URL — публичный URL-префикс, по которому браузер сможет запросить загруженный файл.
MEDIA_URL = '/media/'

# MEDIA_ROOT — папка на диске, куда Django будет сохранять загруженные файлы.
MEDIA_ROOT = BASE_DIR / 'media'


