# Generated by Django 6.0.5 on 2026-05-27 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('inbound', 'Приход'), ('sale', 'Продажа'), ('return', 'Возврат'), ('write_off', 'Списание'), ('reserve', 'Резерв'), ('unreserve', 'Снятие резерва')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('source_type', models.CharField(blank=True, max_length=50)),
                ('source_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product')),
            ],
        ),
    ]
