# Generated by Django 6.0.5 on 2026-05-29 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_options_alter_product_description_and_more'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'verbose_name': 'Движение склада', 'verbose_name_plural': 'Движения склада'},
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('inbound', 'Приход'), ('sale', 'Продажа'), ('return', 'Возврат'), ('write_off', 'Списание'), ('reserve', 'Резерв'), ('unreserve', 'Снятие резерва')], max_length=20, verbose_name='Тип движения'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='source_id',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ID источника'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='source_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тип источника'),
        ),
    ]
